[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "acme_ca_server"
version = "0.0.1"
description = "A sample ACME CA server project"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
keywords = ["acme", "ca", "server"]